api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  grpc:
    address: ":18080"

providers:
  etcd:
    endpoints:
      - "192.168.50.85:2379"
    rootKey: "traefik"

experimental:
  localPlugins:
    demo:
      moduleName: gitee.com/infraboard/traefik-plugin-demo