version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #设置使用jvm内存大小
      - TZ=Asia/Shanghai
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:8.1.3
    container_name: kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" #设置访问elasticsearch的地址
      - TZ=Asia/Shanghai
    ports:
      - 5601:5601
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.1.3
    container_name: apm-server
    user: apm-server
    depends_on:
      - elasticsearch 
    volumes:
      - "./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml" 
    ports:
      - 8200:8200

